In [1]:
from astropy.io import fits
import numpy as np
from astropy.table import Table
import pandas as pd
from tqdm.notebook import tqdm


# random with shuffle 

In [2]:
filename = '../BOSS_North/random0_DR12v5_CMASSLOWZTOT_North.fits'
#filename = '../BOSS_South/random0_DR12v5_CMASSLOWZTOT_South.fits'


hdul = fits.open(filename)


# Access a specific HDU (Header/Data Unit)
data = hdul[1].data  # Assuming the galaxy catalog is in the first extension

In [ ]:

# Print information about the FITS file
hdul.info()

# Print the column names
#print(data.columns)
print(data.names)

In [3]:
#redshifts binning
z1 = 0.2
z2 = 0.5
z3 = 0.75

I split the catalog in two redshifts binning: [0.2,0.5) and [0.5,0.75)

In [4]:
data_low = data[(data['Z']>=z1) & (data['Z']<z2)]

In [5]:
data_high = data[(data['Z']>=z2) & (data['Z']<z3)]

In [6]:
ra_low = data_low['RA']  
dec_low = data_low['DEC']  
z_low = data_low['Z']
w_fkp_low = data_low['WEIGHT_FKP']
density_low  = data_low['NZ']

In [7]:
#check
z_low

array([0.48592052, 0.44922829, 0.47437418, ..., 0.25791413, 0.44536167,
       0.43715981], dtype='>f8')

In [7]:
ra_high = data_high['RA']  
dec_high = data_high['DEC']  
#z = data['REDSHIFT']
z_high = data_high['Z']
w_fkp_high = data_high['WEIGHT_FKP']
density_high  = data_high['NZ']

I shuffle both the random catalogs

In [8]:
index= np.arange(0,len(ra_low),1)
print(index)
np.random.shuffle(index)
print(index)
ra_low = ra_low[index]
dec_low = dec_low[index]
z_low = z_low[index]
w_fkp_low = w_fkp_low[index]
density_low=density_low[index]

[       0        1        2 ... 21653137 21653138 21653139]
[ 5610792   781021 14728071 ... 14781700 13160413   267494]


In [10]:
#check
print(z_low)

[0.45004764 0.21679512 0.37205508 ... 0.29422539 0.47456196 0.47781506]


In [9]:
index= np.arange(0,len(ra_high),1)
print(index)
np.random.shuffle(index)
print(index)
ra_high = ra_high[index]
dec_high = dec_high[index]
z_high = z_high[index]
w_fkp_high = w_fkp_high[index]
density_high=density_high[index]

[       0        1        2 ... 22768145 22768146 22768147]
[19527831  5629943 11598522 ... 14575698  7577143   554888]


fits catalogs file for the xi

In [10]:
def write_header(hdu, filename):
    hdu.name = 'CATALOG'
    hdu.header["EXTNAME"] = 'CATALOG '
    hdu.header["FILENAME"] = filename
    hdu.header["TELESCOP"] = 'BOSS '
    hdu.header["INSTRUME"] = "BOSS DR12"
    hdu.header["CAT_TYPE"] = 'NOT_PROXY'
    hdu.header["CAT_NAME"] = ""
    hdu.header["COORD"] = "EQUATORIAL"
    hdu.header["ANGLE"] = "DEG"
    hdu.header["SELECT"] = "EUCLIDLIKE"

In [11]:
filename = '../BOSS_North/random0_North_low_E.fits'
#filename = '../BOSS_South/random0_South_low_E.fits'

t = fits.BinTableHDU(Table([ra_low, dec_low, z_low ,w_fkp_low], names=('RA', 'DEC', 'REDSHIFT','WEIGHT_FKP')))
write_header(t, filename.split("/")[-1])
t.writeto(filename, overwrite=True)

In [12]:
filename = '../BOSS_North/random0_North_high_E.fits'
#filename = '../BOSS_South/random0_South_high_E.fits'

t = fits.BinTableHDU(Table([ra_high, dec_high, z_high, w_fkp_high ], names=('RA', 'DEC', 'REDSHIFT','WEIGHT_FKP')))
write_header(t, filename.split("/")[-1])
t.writeto(filename, overwrite=True)

fits catalog for the pk

In [15]:
def write_header(hdu, filename):
    hdu.name = 'CATALOG'
    hdu.header["EXTNAME"] = 'CATALOG '
    hdu.header["FILENAME"] = filename
    hdu.header["TELESCOP"] = 'BOSS '
    hdu.header["INSTRUME"] = "BOSS DR12"
    hdu.header["CAT_TYPE"] = 'NOT_PROXY'
    hdu.header["CAT_NAME"] = ""
    hdu.header["COORD"] = "PSEUDO_EQUATORIAL"
    hdu.header["ANGLE"] = "DEG"
    hdu.header["SELECT"] = "EUCLIDLIKE"
    hdu.header["AREA"] = 2763.927572180538

In [16]:
#filename = '../BOSS_North/random0_North_low_C.fits'
filename = '../BOSS_South/random0_South_low_C.fits'

t = fits.BinTableHDU(Table([ra_low, dec_low, z_low ], names=('RA', 'DEC', 'REDSHIFT')))
write_header(t, filename.split("/")[-1])
t.writeto(filename, overwrite=True)

In [17]:
#filename = '../BOSS_North/random0_North_high_C.fits'
filename = '../BOSS_South/random0_South_high_C.fits'

t = fits.BinTableHDU(Table([ra_high, dec_high, z_high ], names=('RA', 'DEC', 'REDSHIFT')))
write_header(t, filename.split("/")[-1])
t.writeto(filename, overwrite=True)

In [18]:
hdul.close()

# galaxy

In [2]:
# Open the FITS file
#filename = '../BOSS_North/galaxy_DR12v5_CMASSLOWZTOT_North.fits'
filename = '../BOSS_South/galaxy_DR12v5_CMASSLOWZTOT_South.fits'

hdul = fits.open(filename)


# Access a specific HDU (Header/Data Unit)
data = hdul[1].data  # Assuming the galaxy catalog is in the first extension

In [ ]:
#only for galaxy 
# Access data in a specific column

ra = data['RA']  
dec = data['DEC']  
z = data['Z']
w_fkp = data['WEIGHT_FKP']
w_cp = data['WEIGHT_CP']
w_noz = data['WEIGHT_NOZ']
w_star = data['WEIGHT_STAR']
w_seeing = data['WEIGHT_SEEING']
w_systot = data['WEIGHT_SYSTOT']
density  = data['NZ']

print(z)
print(w_systot)

In [3]:
#redshifts binning
z1 = 0.2
z2 = 0.5
z3 = 0.75

In [4]:
data_low = data[(data['Z']>=z1) & (data['Z']<z2)]
data_high = data[(data['Z']>=z2) & (data['Z']<z3)]

In [5]:
ra_low = data_low['RA']  
dec_low = data_low['DEC']  
z_low = data_low['Z']
w_fkp_low = data_low['WEIGHT_FKP']
density_low  = data_low['NZ']
w_fkp_low = data_low['WEIGHT_FKP']
w_cp_low = data_low['WEIGHT_CP']
w_noz_low = data_low['WEIGHT_NOZ']
w_star_low = data_low['WEIGHT_STAR']
w_seeing_low = data_low['WEIGHT_SEEING']
w_systot_low= data_low['WEIGHT_SYSTOT']

In [6]:
ra_high = data_high['RA']  
dec_high = data_high['DEC']  
z_high = data_high['Z']
w_fkp_high = data_high['WEIGHT_FKP']
density_high  = data_high['NZ']
w_cp_high = data_high['WEIGHT_CP']
w_noz_high = data_high['WEIGHT_NOZ']
w_star_high = data_high['WEIGHT_STAR']
w_seeing_high = data_high['WEIGHT_SEEING']
w_systot_high = data_high['WEIGHT_SYSTOT']

$ w_{tot} = w_{fkp}w_{sys}(w_{cp}+w_{oz}-1) $

In [8]:
#merging wcp and woz
w_z_low = []

for i in range (0,w_cp_low.size):
    w_z_low = np.append(w_z_low,w_cp_low[i] + w_noz_low[i] - 1)


In [9]:
#merging all weights
w_systot_low = w_systot_low*w_z_low
w_temp_low = w_z_low*w_star_low
w_tot_low = w_systot_low*w_fkp_low

In [10]:
#merging wcp and woz
w_z_high = []

for i in range (0,w_cp_high.size):
    w_z_high = np.append(w_z_high,w_cp_high[i] + w_noz_high[i] - 1)

In [11]:
#merging all weights
w_systot_high = w_systot_high*w_z_high
w_temp_high = w_z_high*w_star_high
w_tot_high = w_systot_high*w_fkp_high

fits catalogs fot the xi

In [12]:
def write_header(hdu, filename):
    hdu.name = 'CATALOG'
    hdu.header["EXTNAME"] = 'CATALOG '
    hdu.header["FILENAME"] = filename
    hdu.header["TELESCOP"] = 'BOSS '
    hdu.header["INSTRUME"] = "BOSS DR12"
    hdu.header["CAT_TYPE"] = 'NOT_PROXY'
    hdu.header["CAT_NAME"] = ""
    hdu.header["COORD"] = "EQUATORIAL"
    hdu.header["ANGLE"] = "DEG"
    hdu.header["SELECT"] = "EUCLIDLIKE"

In [13]:
#filename = '../BOSS_North/galaxy_North_low_E.fits'
filename = '../BOSS_South/galaxy_South_low_E.fits'

t = fits.BinTableHDU(Table([ra_low, dec_low, z_low ,w_cp_low, w_z_low,w_temp_low,w_systot_low,w_tot_low ], names=('RA', 'DEC', 'REDSHIFT', 'WEIGHT_CP', 'WIGHT_Z','WEIGHT_STAR','WEIGHT_SYSTOT','WEIGHT_TOT')))
write_header(t, filename.split("/")[-1])
t.writeto(filename, overwrite=True)

In [14]:
#filename = '../BOSS_North/galaxy_North_high_E.fits'
filename = '../BOSS_South/galaxy_South_high_E.fits'

t = fits.BinTableHDU(Table([ra_high, dec_high, z_high ,w_cp_high, w_z_high,w_temp_high,w_systot_high,w_tot_high ], names=('RA', 'DEC', 'REDSHIFT', 'WEIGHT_CP', 'WIGHT_Z','WEIGHT_STAR','WEIGHT_SYSTOT','WEIGHT_TOT')))
write_header(t, filename.split("/")[-1])
t.writeto(filename, overwrite=True)

fits catalogs for the pk

In [ ]:
def write_header(hdu, filename):
    hdu.name = 'CATALOG'
    hdu.header["EXTNAME"] = 'CATALOG '
    hdu.header["FILENAME"] = filename
    hdu.header["TELESCOP"] = 'BOSS '
    hdu.header["INSTRUME"] = "BOSS DR12"
    hdu.header["CAT_TYPE"] = 'NOT_PROXY'
    hdu.header["CAT_NAME"] = ""
    hdu.header["COORD"] = "PSEUDO_EQUATORIAL"
    hdu.header["ANGLE"] = "DEG"
    hdu.header["SELECT"] = "EUCLIDLIKE"
    hdu.header["AREA"] = 2763.927572180538

In [ ]:
#filename = '../BOSS_North/galaxy_North_low_C.fits'
filename = '../BOSS_South/galaxy_South_low_C.fits'

t = fits.BinTableHDU(Table([ra_low, dec_low, z_low ,w_cp_low, w_z_low,w_temp_low,w_systot_low,w_tot_low ], names=('RA', 'DEC', 'REDSHIFT', 'WEIGHT_CP', 'WIGHT_Z','WEIGHT_STAR','WEIGHT_SYSTOT','WEIGHT_TOT')))
write_header(t, filename.split("/")[-1])
t.writeto(filename, overwrite=True)

In [ ]:
#filename = '../BOSS_North/galaxy_North_high_C.fits'
filename = '../BOSS_South/galaxy_South_high_C.fits'

t = fits.BinTableHDU(Table([ra_high, dec_high, z_high ,w_cp_high, w_z_high,w_temp_high,w_systot_high,w_tot_high ], names=('RA', 'DEC', 'REDSHIFT', 'WEIGHT_CP', 'WIGHT_Z','WEIGHT_STAR','WEIGHT_SYSTOT','WEIGHT_TOT')))
write_header(t, filename.split("/")[-1])
t.writeto(filename, overwrite=True)

# I try to extract dndz for pk (claudio)

In [12]:
def write_header(hdu, filename):
    hdu.name = 'CATALOG'
    hdu.header["EXTNAME"] = 'CATALOG '
    hdu.header["FILENAME"] = filename
    hdu.header["TELESCOP"] = 'BOSS '
    hdu.header["INSTRUME"] = "BOSS DR12"
    hdu.header["CAT_TYPE"] = 'NOT_PROXY'
    hdu.header["CAT_NAME"] = ""
    hdu.header["COORD"] = "PSEUDO_EQUATORIAL"
    hdu.header["ANGLE"] = "DEG"
    hdu.header["SELECT"] = "EUCLIDLIKE"

In [13]:
# Open the FITS file
filename = 'BOSS_North/galaxy_CMASSLOWZTOT_North_C.fits'

hdul = fits.open(filename)


# Access a specific HDU (Header/Data Unit)
#data = hdul[1].data  

In [14]:
data = hdul[1].data 

In [15]:
density = data['NZ']

In [17]:
filename = 'BOSS_North/galaxy_CMASSLOWZTOT_North_density.fits'
t = fits.BinTableHDU(Table([ra, dec, z,density  ], names=('RA', 'DEC', 'REDSHIFT', 'NZ',)))
write_header(t, filename.split("/")[-1])
t.writeto(filename, overwrite=True)

In [ ]:
from astropy.io import fits
from astropy.table import Table

# Open the FITS file
filename = 'BOSS_North/galaxy_DR12v5_CMASSLOWZTOT_North.fits'
hdul = fits.open(filename)

# Print information about the FITS file
#hdul.info()

# Access the Binary Table HDU (assuming the table is in the first extension)
hdu = hdul[1]

# Convert the table data to an Astropy Table
table = Table(hdu.data)

# Print the column names and the first few rows of the table
#print(table.colnames)
print(table[:5])

# Alternatively, convert the table data to a NumPy array
#data = hdu.data
#print(data.names)
#print(data[:5])

# Close the FITS file
#hdul.close()


        RA                 DEC         RUN ... ICOLLIDED INGROUP MULTGROUP
------------------ ------------------- --- ... --------- ------- ---------
195.07128497875797 -0.5907713163844767 745 ...         0   35880         1
195.02299176985144 -0.6109986068739428 745 ...         0    8843         1
195.07974105207435 0.34898067241979264 745 ...         0   13065         2
 195.1705738058857  0.3598641895951883 745 ...         0   12492         1
 195.2042890842218  0.3472671634337523 745 ...         0    2060         1
