# Basic Probability Calculations


In [80]:
# Usefull imports
import numpy as np
import matplotlib.pyplot as plt

In [82]:
def pdf(x_range, A, w):
    '''
    Args:
    - x_range: Tuple (min, max) defining the range of x values
    - A: Amplitude of the sine wave
    - w: Frequency of the sine wave 
    
    
    Returns:
    - numpy arrays representing x and y as defined below
    '''
    x_min, x_max = x_range
    
    x = np.linspace(x_min, x_max, 100)
    
    y = A*np.sin(w*x)**2
    
    return x, y

# Example usage:
x_range = (-5, 5)
A = 1
w = 1


x_values, y_values = pdf(x_range, A, w)

# Plotting the distribution
plt.plot(x_values, y_values)
plt.title('2D Distribution (Square of Sine Wave)')
plt.xlabel('X values')
plt.ylabel('Probability')
plt.grid(True)
plt.show()

In [77]:
# define a function that would give you a 2D distribution. Do not pick a Gaussian.
"""
def pdf(x_range, y_range, frequency_x, frequency_y):
    '''
    Args:
    - x_range: Tuple (min, max) defining the range of x values
    - y_range: Tuple (min, max) defining the range of y values
    - frequency_x: Frequency of the sine wave along the x-axis
    - frequency_y: Frequency of the sine wave along the y-axis
    
    Returns:
    - 2D numpy arrays representing the meshgrid coordinates (X, Y) and the distribution (Z)
    '''
    x_min, x_max = x_range
    y_min, y_max = y_range
    
    x = np.linspace(x_min, x_max, 100)
    y = np.linspace(y_min, y_max, 100)
    
    X, Y = np.meshgrid(x, y) #grids of point such as we have all combinations of x with y and viceversa
    
    Z = np.sin(frequency_x * X)**2 * np.sin(frequency_y * Y)**2
    
    return X, Y, Z

# Example usage:
x_range = (-5, 5)
y_range = (-5, 5)
frequency_x = 1
frequency_y = 2

X, Y, distribution = pdf(x_range, y_range, frequency_x, frequency_y)

# Plotting
plt.figure(figsize=(8, 6))
plt.imshow(distribution, extent=[x_range[0], x_range[1], y_range[0], y_range[1]], origin='lower', cmap='viridis')
plt.colorbar(label='Density')
plt.xlabel('X')
plt.ylabel('Y')
plt.title('2D Distribution')
plt.grid(False)
plt.show()
"""

"\ndef pdf(x_range, y_range, frequency_x, frequency_y):\n    '''\n    Args:\n    - x_range: Tuple (min, max) defining the range of x values\n    - y_range: Tuple (min, max) defining the range of y values\n    - frequency_x: Frequency of the sine wave along the x-axis\n    - frequency_y: Frequency of the sine wave along the y-axis\n    \n    Returns:\n    - 2D numpy arrays representing the meshgrid coordinates (X, Y) and the distribution (Z)\n    '''\n    x_min, x_max = x_range\n    y_min, y_max = y_range\n    \n    x = np.linspace(x_min, x_max, 100)\n    y = np.linspace(y_min, y_max, 100)\n    \n    X, Y = np.meshgrid(x, y) #grids of point such as we have all combinations of x with y and viceversa\n    \n    Z = np.sin(frequency_x * X)**2 * np.sin(frequency_y * Y)**2\n    \n    return X, Y, Z\n\n# Example usage:\nx_range = (-5, 5)\ny_range = (-5, 5)\nfrequency_x = 1\nfrequency_y = 2\n\nX, Y, distribution = pdf(x_range, y_range, frequency_x, frequency_y)\n\n# Plotting\nplt.figure(figsiz

In [78]:
# define a prior box:
# - on paraeters A and w or on x?
# - how do I do a box? it's meshgrid command?
A_array = np.linspace(0.1, 2, 100)
w_array = np.linspace(0.1, 2, 100)
parA, parW = np.meshgrid(A_array, w_array) #grids of point such as we have all combinations of x with y and viceversa
print(parA)
print(parW)

[[0.1        0.11919192 0.13838384 ... 1.96161616 1.98080808 2.        ]
 [0.1        0.11919192 0.13838384 ... 1.96161616 1.98080808 2.        ]
 [0.1        0.11919192 0.13838384 ... 1.96161616 1.98080808 2.        ]
 ...
 [0.1        0.11919192 0.13838384 ... 1.96161616 1.98080808 2.        ]
 [0.1        0.11919192 0.13838384 ... 1.96161616 1.98080808 2.        ]
 [0.1        0.11919192 0.13838384 ... 1.96161616 1.98080808 2.        ]]
[[0.1        0.1        0.1        ... 0.1        0.1        0.1       ]
 [0.11919192 0.11919192 0.11919192 ... 0.11919192 0.11919192 0.11919192]
 [0.13838384 0.13838384 0.13838384 ... 0.13838384 0.13838384 0.13838384]
 ...
 [1.96161616 1.96161616 1.96161616 ... 1.96161616 1.96161616 1.96161616]
 [1.98080808 1.98080808 1.98080808 ... 1.98080808 1.98080808 1.98080808]
 [2.         2.         2.         ... 2.         2.         2.        ]]


In [79]:
# sample your reference probability on a 2D regular grid in the prior box
# - then I suppose on A and w  
# - supposing I have meshgrid, what do I do? I pass those parameters arrays to my pdf?

# Initialize arrays to store x and y values of the same form of parA and parW with all zeros
x_grid = np.zeros_like(parA) 
y_grid = np.zeros_like(parW)
# Compute x and y values for each combination of parameters
for i in range(parA.shape[0]):
    for j in range(parA.shape[1]):
        A = parA[i, j]
        w = parW[i, j]
        x_grid[i, j], y_grid[i, j] = pdf(x_range, A, w)

ValueError: setting an array element with a sequence.

In [ ]:
# normalize the pdf
# - do I need to performe a 2D integral over A and w or just over x?
# - According to what I see after, a 2D integral. However, over tre prior box I suppose?  

In [ ]:
# contour plot the distribution (on generic iso-contours, the default ones work)

In [ ]:
# marginalize the distribution and get two 1D distributions. Plot them.

In [ ]:
# check that marginalization does not alter the normalization of the pdf.

In [ ]:
# calculate the cumulative distribution function of the 1D distribution. Plot it.

In [ ]:
# calculate the mean, median and mode. Add them to the plot.

In [ ]:
# calculate the variance of the 1D distribution. Add to the plot the Gaussian approximation of your distribution.

In [ ]:
# calculate and plot the 68% HPD region for the 1D distribution. Plot it.

In [ ]:
# make a 2D contour plot of the 2D 68% HPD region. How does it relate to the 1D region?