In [1]:
import sys
sys.path.append("/mnt/c/Users/dambr/Desktop/AstroCosmoComputational/Students/Anna_DAmbrosio/")

import numpy as np
import matplotlib.pyplot as plt
plt.rcParams.update({
    "text.usetex": False,
    "font.family": "serif",})

# Import pyACC logger
#from pyACC.helpers import Logger

# Set the logger
#print = Logger("pyACC.CosmologicalDistances")

# Import your integration methods
from pyACC.Calculus import intgr

# Import integration class
from pyACC.cosmology import *

import scipy as sp
from scipy import interpolate

In [2]:
# definition of distance modulus
def mu(z, H0, O_m, N_int):
    d_mu = np.zeros((N_int,N_int,N_int))
    for zi,zeta in enumerate(z):
        for hi, acca in enumerate(H0):
            for O_mi, oemme in enumerate(O_m):
                O_de_m = 1 - oemme
                d_mu[zi,hi,O_mi] = distance_modulus(zeta.item(), H_0=acca, O_m=oemme, O_gam = 0.0, O_nu = 0.0, O_de = O_de_m, w_de = -1)
    return d_mu
# mu = lambda z, H0, O_m, O_rad, O_nu, O_de, w_de: 5*np.log10(luminosity_distance(z, H0, O_m, O_rad, O_nu, O_de, w_de))

In [8]:
# definition of vector of points for the interpolation
N = 5
z_points = np.linspace(0.1,1,N)
H0_points = np.linspace(65.0,75.0,N)
Om_points = np.linspace(0.1,1.0,N)

In [9]:
# evaluation of mu in points
values = mu(z_points, H0_points, Om_points, N)

In [12]:
# creation of the grid
point_grid = np.column_stack((z_points,H0_points,Om_points))
Z, H0, Om = np.meshgrid(z_points, H0_points, Om_points)
point = np.array([Z, H0,Om]).T

In [15]:
# interpolation
list_point = [z_points, H0_points, Om_points]
mu_val = sp.interpolate.interpn((z_points, H0_points, Om_points),values,point)
print(mu_val)

[[[ 8.51571616  8.43376408  8.35479274  8.27859291  8.20497662]
  [11.49222951 11.41027743 11.3313061  11.25510627 11.18148998]
  [13.03123115 12.94927907 12.87030773 12.7941079  12.72049161]
  [14.1577374  14.07578532 13.99681399 13.92061415 13.84699787]
  [15.07819764 14.99624556 14.91727422 14.84107439 14.7674581 ]]

 [[ 8.47672764  8.39477556  8.31580422  8.23960439  8.16598811]
  [11.34822794 11.26627586 11.18730452 11.11110469 11.0374884 ]
  [12.75984586 12.67789378 12.59892245 12.52272261 12.44910633]
  [13.74123256 13.65928048 13.58030914 13.50410931 13.43049303]
  [14.50506022 14.42310814 14.3441368  14.26793697 14.19432069]]

 [[ 8.43968454  8.35773246  8.27876112  8.20256129  8.128945  ]
  [11.22634772 11.14439563 11.0654243  10.98922447 10.91560818]
  [12.55391434 12.47196226 12.39299092 12.31679109 12.24317481]
  [13.45454854 13.37259646 13.29362512 13.21742529 13.143809  ]
  [14.14233698 14.0603849  13.98141356 13.90521373 13.83159745]]

 [[ 8.40438491  8.32243283  8.2434